title: Fábio Tuda # your name (or website title) here
logo: "/images/profile_picture.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst & BI Developer. Transforming complex datasets into actionable insights
  <br><br>

Skills: SQL | Tableau | PowerBI | Excel | Python

  <br><br>
  <a href="https://www.linkedin.com/in/fabiohtuda/?locale=en_US">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
